obj-m += nu1l.o

CC=gcc

all:
	make -C '/home/bird/ctf/N1CTF/nu1l/initramfs_root/lib/modules/4.15.6/build/' M=$(PWD) modules
clean:
	make -C '/home/bird/ctf/N1CTF/nu1l/initramfs_root/lib/modules/4.15.6/build/' M=$(PWD) clean